#!/bin/bash

#"usage:\n"
#"bitmap option inputfile.bmp outputfile.bmp\n"
#"options:\n"
#"  -n no transform\n"
#"  -c cell shade\n"
#"  -g gray scale\n"
#"  -p pixelate\n"
#"  -b blur\n"
#"  -r90 rotate 90\n"
#"  -r180 rotate 180\n"
#"  -r270 rotate 270\n"
#"  -v flip vertically\n"
#"  -h flip horizontally\n"
#"  -d1 flip diagonally 1\n"
#"  -d2 flip diagonally 2\n"
#"  -grow scale the image by 2\n"
#"  -shrink scale the image by .5" << endl;

             
while read filename
do
    echo "\nRunning bitmap on $filename\n"
    ./bitmap -n      examples/"$filename".bmp results/"$filename".bmp
    ./bitmap -c      examples/"$filename".bmp results/"$filename"_cell.bmp
    ./bitmap -g      examples/"$filename".bmp results/"$filename"_grey.bmp
    ./bitmap -p      examples/"$filename".bmp results/"$filename"_pixel.bmp
    ./bitmap -b      examples/"$filename".bmp results/"$filename"_blur.bmp
    ./bitmap -r90    examples/"$filename".bmp results/"$filename"_r90.bmp
    ./bitmap -r180   examples/"$filename".bmp results/"$filename"_r180.bmp
    ./bitmap -r270   examples/"$filename".bmp results/"$filename"_r270.bmp
    ./bitmap -v      examples/"$filename".bmp results/"$filename"_vert.bmp
    ./bitmap -h      examples/"$filename".bmp results/"$filename"_hori.bmp
    ./bitmap -d1     examples/"$filename".bmp results/"$filename"_diag1.bmp
    ./bitmap -d2     examples/"$filename".bmp results/"$filename"_diag2.bmp
    ./bitmap -grow   examples/"$filename".bmp results/"$filename"_grow.bmp
    ./bitmap -shrink examples/"$filename".bmp results/"$filename"_shrink.bmp
done < bitmapnames.txt
